### PR TITLE
Improve error handling

### PR DESCRIPTION
**Pull request by adamreisnz**
- Throw actual errors so we get a proper stack trace
- Provide more detail for invalid pin errors

### CODE REVIEW

**Comment by adamreisnz** [comment]
@jperkin are you able to merge this please?

**Comment by jperkin** [comment]
Yeh I'll look at this this week, thanks.

**Comment by jperkin** [comment]
Merged, thanks!

**Comment by adamreisnz** [comment]
@jperkin thanks, are you able to release this to a new version on NPM soon?

**Comment by jperkin** [comment]
I already did, 0.9.20.

**Comment by adamreisnz** [comment]
Cheers thanks

**Pull request closed without merging**
