### PR TITLE
Support for SUNXI chipset (NanoPI & OrangePI)

### PR DESCRIPTION
**Pull request by lubino**
Hello, I did it again, this time in a more clean way, please let me know that this time it is acceptable.

### CODE REVIEW

**Comment by sivambigaim** [comment]
Hello,
I have used your source in NanoPi M1 verison.. I am facing the following issue.
Could you help me ?
/home/pi/siva/lubino_rpio/node-rpio/lib/rpio.js:104
        return bindfunc(optarg);
               ^

Error: Could not initialize sunxi GPIO library
    at Error (native)
    at bindcall (/home/pi/siva/lubino_rpio/node-rpio/lib/rpio.js:104:9)
    at rpio.init (/home/pi/siva/lubino_rpio/node-rpio/lib/rpio.js:552:2)
    at rpio.open (/home/pi/siva/lubino_rpio/node-rpio/lib/rpio.js:562:18)
    at Object.<anonymous> (/home/pi/siva/lubino_rpio/node-rpio/examples/button.js:16:6)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by lubino** [comment]
It looks like the "npm install" did not compile the library, can you please delete "node_modules" directory and send me the output from "npm install"?

**Comment by jperkin** [comment]
Hi, just to say thanks for doing this. I'd like to review this but am busy with other stuff at the moment. I'll try to get to it as soon as I can. Thanks.

**Comment by medemi68** [comment]
I might be able to test out his PR on a couple different Orange Pi models that I have. As for whether or not it works on the NanoPi or whether compatibility was broken for any of the RPi models, someone would have to take a look at that.

Lubino, any chance you could tell us what linux distro you were using, (was it Armbian?, or one of the prebuilt images from OPi), I heard there were some issues with the kernel for the base prebuilt images from OPi in regards to SPI support.

Thanks

**Comment by lubino** [comment]
I have tested it on Orange Pi and Nano Pi board both on Armbian, the newest version that time. Now I see that the code is not mergeable, should I solve it first?

**Comment by vanarebane** [comment]
Hi, how to use this library? I have Banana Pi Zero M2 with Allwinner H2+. Thanks! :)

**Comment by lubino** [comment]
@jperkin thank you very much for this.

**Comment by jperkin** [comment]
Thanks again for the PR, sorry that I was terrible at getting back to you and explaining why I wanted to do it differently.  Hope it wasn't too disheartening to put in that work and not have it merged.

**Pull request closed without merging**
